name: Code Quality

on:
  push:
    # TODO - update
    branches: ["dont-run"]
  pull_request:
    branches: ["dont-run"]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        run: biome ci .
